version: 2.1

parameters:
  environment:
    type: string
    default: "dev"

jobs:
    conditional-job:
      docker:
        - image: cimg/base:stable
      steps:
           - when:
               condition:  
                 equal: [ "prod", << pipeline.parameters.environment >> ]
               steps:
                 - checkout
                 - run: echo "this will run when env value matches prod"
           - run: echo "this will run always"
                 
workflows:
  main:
    jobs:
      - conditional-job
