version: 2.1

parameters:
  environment:
    type: string
    default: "dev"

jobs:
    conditional-job:
      docker:
        - image: cimg/base:stable
      steps:
           - when:
               condition:
                 equal: [ "prod", << pipeline.parameters.environment >> ]
               steps:
                 - checkout
                 - run: echo "this will run when env value is prod"
           - when:
               condition:
                 equal: [ "dev", << pipeline.parameters.environment >> ]
               steps:
                 - run: echo "run this when env value is dev"
           - run: echo "this will run always"
                 
workflows:
  main:
    jobs:
      - conditional-job
