version: 2.1

parameters:
  helm-version:
    type: string
    default: "4.0.0"
  values-file:
    type: string
    default: "server-values.yaml"
  k8s-namespace:
    type: string
    default: "<namespace-name>"
  cluster-name:
    type: string
    default: "<cluster-name>"
  nomad-deploy:
    type: boolean
    default: false
  helm-deploy:
    type: boolean
    default: false

jobs:         
  deploy-helm-chart:
    machine: true
    steps:
      - checkout
      - run: 
          name: Install Pre-requisites
          command: |
              echo "Installing Helm..."
              curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
              chmod 700 get_helm.sh
              ./get_helm.sh
              echo "Installing Helm Diff..."
              helm plugin install https://github.com/databus23/helm-diff
              echo "Installing kubectl..."
              curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
              curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
              echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
              sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
              kubectl version --client
              echo "Installing eksctl..."
              curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
              sudo mv /tmp/eksctl /usr/local/bin
              eksctl version
              mv server-helm/support-values.yaml .
      - run:
          name: Login to Azure and Pull Helm Charts
          command: |
              helm registry login cciserver.azurecr.io -u $AZURECR_USER -p $AZURECR_PWD
              sleep 5
              helm pull oci://cciserver.azurecr.io/circleci-server --version << pipeline.parameters.helm-version >>      
      - run:
          name: Write Kubeconfig
          command: |
              eksctl get clusters 
              eksctl utils write-kubeconfig --cluster=<< pipeline.parameters.cluster-name >>
          no_output_timeout: 3h    
      - run:
          name: Get Pod Health
          command: | 
            kubectl get pods -n << pipeline.parameters.k8s-namespace >>
      - run:
          name: Stage Charts
          command: |
            tar xvf circleci-server-<< pipeline.parameters.helm-version >>.tgz
            ls -lah
            pwd
      - run: 
          name: Capture Diff between deploy versions
          command: |
             helm diff upgrade server -f << pipeline.parameters.values-file >> circleci-server -n << pipeline.parameters.k8s-namespace >>
      - run: 
          name: Deploy Helm Chart version to Cluster
          command: |
             helm upgrade --install server -f << pipeline.parameters.values-file >> circleci-server -n << pipeline.parameters.k8s-namespace >>
            
workflows:
  server4-helm-deploy:
    when: << pipeline.parameters.helm-deploy >>
    jobs:
      - deploy-helm-chart:
           context: server

