version: 2.1

parameters:
  environment:
    type: string
    default: "dev"

jobs:
    conditional-step-job:
      docker:
        - image: cimg/base:stable
      steps:
           - run: echo "run always"
           - run:
               name: "Run on Failure"
               command: echo "this will run only on failure"
               when: on_fail
           - run: 
               name: "Run on Success"
               command: echo "this will run always"
               when: on_success
                 
workflows:
  main:
    jobs:
      - conditional-job
